name: test and push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build Docker Compose
      run: |
        docker-compose up -d

    # - name: Run test using pytest
    #   run: |
    #     docker exec memoar_fastapi_1 python pytest.py

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    # - name: Build Docker Image
    #   run: |
    #     docker build -t siuvicorn .

    # - name: Run Docker Container
    #   run: |
    #     docker run -d -p 8000:8000 siuvicorn

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r tests/requirements.txt

    - name: Run tests
      run: python tests/pytest.py